[package]
name = "doom"
version = "1.10.1"
authors = ["id Software", "Alexander Hill <ahill@breadpudding.dev>"]
edition = "2021"
readme = "readme.txt"
license = "GPL-2.0-only"
publish = false

[dependencies]
byte-strings = "^0.2.2"

[build-dependencies]
bindgen = "^0.59.2"